server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://178.141.253.196:5432/mp_system_external_db
    username: postgres
    password: 1
  jackson:
    date-format: "org.openapitools.RFC3339DateFormat"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

rabbitmq:
  host: 178.141.253.196
  port: 5672
  username: user_microservice_external
  password: password_microservice_external

cors:
  allowedOrigins: "https://api.ucheter.ru, https://ucheter.ru, http://localhost:3000, http://localhost:8080"
  allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
  allowedHeaders: "*"
  allowedCredentials: true
  corsConfiguration: "/**"
  maxAge: 3600