server:
  port=8081
spring:
  jackson:
    date-format: "org.openapitools.RFC3339DateFormat"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

cors:
  allowedOrigins: "https://api.ucheter.ru, https://ucheter.ru, http://localhost:3000, http://localhost:8080"
  allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
  allowedHeaders: "*"
  allowedCredentials: true
  corsConfiguration: "/**"
  maxAge: 3600